---

- name: Common stuff for all the server
  hosts: all
  sudo: yes
  gather_facts: no
  roles:
    - { role: contrib/dgnest.authorization, when: "user != 'vagrant'" }
    - common
  tags:
    - all
    - common
    - authorization

- name: execute roles dependences
  hosts: webservers
  gather_facts: no
  roles:
    - contrib/dgnest.nodejs
    - contrib/dgnest.nginx
    - contrib/dgnest.supervisor
