# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up
---
version: "3.6"

services:

  app:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    depends_on:
      - mongodb
    environment: &environment
      - APPLICATION_HOST=0.0.0.0
      - APPLICATION_PORT=5000
      - MONGODB_URL=http://mongodb:27017
    volumes:
      - .:/usr/src
    env_file:
      - .env


  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    env_file:
      - .env

volumes:
  mongodb:
  yarn-cache:
